name: aquedact_heros
description: An empty Aqueduct application.
version: 0.0.1
author: s6o

environment:
  sdk: ">=2.3.0 <2.9.0"

dependencies:
  aqueduct: 3.3.0+1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0

dependency_overrides:
  postgres: 2.1.1
